arm:
#  kinematics_solver: 3dof_tm_arm_kinematics/IKFastKinematicsPlugin
  kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
